on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'public/**'

jobs:
    build_vue:
        runs-on: ubuntu-latest
        name: Build Vue
        steps:
            - uses: actions/checkout@v2

            - id: Build-Vue
              uses: xRealNeon/VuePagesAction@1.0.1
              with:
                  username: 'VSmert'
                  reponame: 'doodle-frontend'
                  gitemail: 'CI@vsmert.github.io'
                  token: ${{ secrets.GITHUB_TOKEN }}
